### ISSUE TITLE
dicom_to_nifti error if nifti output path is inside the dicom directory

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#119]
### Bug Description
In dicom_to_nifti API, [copy_tree](https://github.com/shimming-toolbox/shimming-toolbox/blob/42bdddfd35e6a5140e65b344d4a615eab4e9492c/shimmingtoolbox/dicom_to_nifti.py#L38) function recursively copies the niftis within the dicom directory.

<details>
 <summary>Terminal output</summary>

```
from shimmingtoolbox.dicom_to_nifti import dicom_to_nifti
path_dicoms = "testing_data/realtime_zshimming_data"
path_nifti = "testing_data/realtime_zshimming_data/nifti"
subject = "subject-01"
dicom_to_nifti(path_dicoms, path_nifti, subject_id=subject)
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/file_util.py", line 41, in _copy_file_contents
    fdst = open(dst, 'wb')
OSError: [Errno 63] File name too long: 'testing_data/realtime_zshimming_data/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/17_gre_realtime_zshim_UNSHIMMED_2/echo_8.5/acdc_112p-HE1-4;NE1,2-0018-001.dcm'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/alex/Documents/School/Polytechnique/Master/project/shimming-toolbox/shimmingtoolbox/dicom_to_nifti.py", line 38, in dicom_to_nifti
    copy_tree(path_dicom, os.path.join(path_nifti, 'sourcedata'))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/dir_util.py", line 159, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/dir_util.py", line 159, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/dir_util.py", line 159, in copy_tree
    verbose=verbose, dry_run=dry_run))
  [Previous line repeated 105 more times]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/dir_util.py", line 163, in copy_tree
    dry_run=dry_run)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/file_util.py", line 151, in copy_file
    _copy_file_contents(src, dst)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/file_util.py", line 44, in _copy_file_contents
    "could not create '%s': %s" % (dst, e.strerror))
distutils.errors.DistutilsFileError: could not create 'testing_data/realtime_zshimming_data/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/nifti/sourcedata/17_gre_realtime_zshim_UNSHIMMED_2/echo_8.5/acdc_112p-HE1-4;NE1,2-0018-001.dcm': File name too long
```

</details>

### Reproduction Steps
```
from shimmingtoolbox.dicom_to_nifti import dicom_to_nifti
path_dicoms = "testing_data/realtime_zshimming_data"
path_nifti = "testing_data/realtime_zshimming_data/nifti"
subject = "subject-XX"
dicom_to_nifti(path_dicoms, path_nifti, subject_id=subject)
```

Note: Any nifti path that is inside the provided dicom directory

### Potential Reasons behind Bug:
This line :[copy_tree](https://github.com/shimming-toolbox/shimming-toolbox/blob/42bdddfd35e6a5140e65b344d4a615eab4e9492c/shimmingtoolbox/dicom_to_nifti.py#L38)

**Comment by 4rnaudB** [comment]
@po09i Fixed?

**Comment by po09i** [comment]
> @po09i Fixed?
I have avoided putting the output path in the DICOM folder since then so I am not sure

**Comment by 4rnaudB** [comment]
Added a check in PR ^^
