### ISSUE TITLE
Issues installing on Big Sur

### ISSUE THREAD

**Issue by ahill187** [shimming-toolbox/shimming-toolbox#229]
### Environment details

- [ ] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html)

Project version:

Operating System and version:

MacOSX 10.16 (Big Sur)
Python Version: 3.8.2
Pip Version: 19.2.3

Path to Python binary: /Users/work/Coding/NeuroPoly/shimming-toolbox/env/bin/python3

### Bug Description
Following the steps in the `README.md`, the installation fails with the following error:

```
    ERROR: Command errored out with exit status 1:
     command: /Users/work/Coding/NeuroPoly/shimming-toolbox/env/bin/python3 /Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/dq/ywj829_54kl2pddsmwy8ry2w0000gp/T/tmpxkhdvzfi
         cwd: /private/var/folders/dq/ywj829_54kl2pddsmwy8ry2w0000gp/T/pip-install-92yja01c/scipy
    Complete output (139 lines):
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE
    
    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE
    
    openblas_clapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas,lapack not found in ['/Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE
    
    flame_info:
    customize UnixCCompiler
      libraries flame not found in ['/Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    accelerate_info:
      NOT AVAILABLE
    
    lapack_info:
    customize UnixCCompiler
      libraries lapack not found in ['/Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE
    
    lapack_src_info:
      NOT AVAILABLE
    
      NOT AVAILABLE
    
    setup.py:460: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /private/var/folders/dq/ywj829_54kl2pddsmwy8ry2w0000gp/T/pip-install-92yja01c/scipy/pip-wheel-metadata'), proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
    Running from SciPy source directory.
    /private/var/folders/dq/ywj829_54kl2pddsmwy8ry2w0000gp/T/pip-build-env-hnbjtqte/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      if getattr(self, '_calc_info_{}'.format(lapack))():
    /private/var/folders/dq/ywj829_54kl2pddsmwy8ry2w0000gp/T/pip-build-env-hnbjtqte/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      if getattr(self, '_calc_info_{}'.format(lapack))():
    Traceback (most recent call last):
      File "/Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/dq/ywj829_54kl2pddsmwy8ry2w0000gp/T/pip-build-env-hnbjtqte/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/dq/ywj829_54kl2pddsmwy8ry2w0000gp/T/pip-build-env-hnbjtqte/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 253, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/private/var/folders/dq/ywj829_54kl2pddsmwy8ry2w0000gp/T/pip-build-env-hnbjtqte/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 583, in <module>
        setup_package()
      File "setup.py", line 579, in setup_package
        setup(**metadata)
      File "/private/var/folders/dq/ywj829_54kl2pddsmwy8ry2w0000gp/T/pip-build-env-hnbjtqte/overlay/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
        config = configuration()
      File "setup.py", line 477, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found. Note: Accelerate is no longer supported.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/work/Coding/NeuroPoly/shimming-toolbox/env/bin/python3 /Users/work/Coding/NeuroPoly/shimming-toolbox/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/dq/ywj829_54kl2pddsmwy8ry2w0000gp/T/tmpxkhdvzfi Check the logs for full command output.
```

### Reproduction Steps

I followed the instructions in the `README`:

1. Download the git repo:
```
mkdir shimming-toolbox
cd shimming-toolbox
git init
git remote add origin https://github.com/shimming-toolbox/shimming-toolbox.git
git pull origin master
```
2. Install `dcm2nixx`:
```
brew install dcm2niix
```
3. Create virtual environment:
```
python3 -m venv env
source env/bin/activate
```
4. Install `shimming-toolbox`:
```
pip3 install -e . 
```

### Potential Reasons behind Bug:
I think it might be related to `Scipy`:
https://github.com/scipy/scipy/issues/13102

### Solution
As suggested on the `Scipy` issue above, I was able to fix this by upgrading `pip` to `21.0.1`:

```
pip3 install --upgrade pip  
```

I think we should describe this in the installation description in the `README`, i.e. specify the pip version required for MacOS Big Sur

**Comment by po09i** [comment]
This is an old installation problem
