### ISSUE TITLE
B1+ shimming fails if the number of Tx channels in the SarDataUser.mat file does not match the number of Tx chanels being used

### ISSUE THREAD

**Issue by dpapp86** [shimming-toolbox/shimming-toolbox#436]
**Overview**
This is to document something that is hopefully an outlier bug. It arises if the number of Tx channels described by the SarDataUser.mat file is different from the number of Tx channels currently used by the coil. This issue arose only once so far, when we were doing remote scanning at the MGH. I have opened this issue to track what, if anything, the solution is.

**Context**
For B1+ shimming option "SAR efficiency", a VOP file (SarDataUser.mat from C:/Medcom/MriProduct/PhysConfig) is a hard requirements, and for the "CV reduction" and "Target" options, it is a soft requirement. MGH was doing scanning for us, and the toolbox failed to produce these shim settings.

These B1+ shim steps will fail if the number of channels in the VOP file is different than the number of channel, with the following error:
**Error log**
https://github.com/shimming-toolbox/shimming-toolbox/blob/7003a7189007c699c9a025c7f81a4926cec99cb8/shimmingtoolbox/shim/b1shim.py#L198
```
Traceback (most recent call last):
  File "/Users/danielpapp/shimming-toolbox/bin/st_b1shim", line 33, in <module>
    sys.exit(load_entry_point('shimmingtoolbox', 'console_scripts', 'st_b1shim')())
  File "/Users/danielpapp/shimming-toolbox/python/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/danielpapp/shimming-toolbox/python/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/danielpapp/shimming-toolbox/python/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/danielpapp/shimming-toolbox/python/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/danielpapp/shimming-toolbox/shimming-toolbox/shimmingtoolbox/cli/b1shim.py", line 71, in b1shim_cli
    shim_weights = b1shim(b1_map, mask=mask_resampled, algorithm=algorithm, target=target, q_matrix=vop,
  File "/Users/danielpapp/shimming-toolbox/shimming-toolbox/shimmingtoolbox/shim/b1shim.py", line 116, in b1shim
    sar_limit = sar_factor * max_sar(vector_to_complex(weights_init), q_matrix)
  File "/Users/danielpapp/shimming-toolbox/shimming-toolbox/shimmingtoolbox/shim/b1shim.py", line 198, in max_sar
    return np.max(np.real(np.matmul(np.matmul(np.conj(weights).T, q_matrix.T), weights)))
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) Traceback (most recent call last):
  File "/Users/danielpapp/shimming-toolbox/bin/st_b1shim", line 33, in <module>
    sys.exit(load_entry_point('shimmingtoolbox', 'console_scripts', 'st_b1shim')())
  File "/Users/danielpapp/shimming-toolbox/python/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/danielpapp/shimming-toolbox/python/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/danielpapp/shimming-toolbox/python/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/danielpapp/shimming-toolbox/python/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/danielpapp/shimming-toolbox/shimming-toolbox/shimmingtoolbox/cli/b1shim.py", line 71, in b1shim_cli
    shim_weights = b1shim(b1_map, mask=mask_resampled, algorithm=algorithm, target=target, q_matrix=vop,
  File "/Users/danielpapp/shimming-toolbox/shimming-toolbox/shimmingtoolbox/shim/b1shim.py", line 116, in b1shim
    sar_limit = sar_factor * max_sar(vector_to_complex(weights_init), q_matrix)
  File "/Users/danielpapp/shimming-toolbox/shimming-toolbox/shimmingtoolbox/shim/b1shim.py", line 198, in max_sar
    return np.max(np.real(np.matmul(np.matmul(np.conj(weights).T, q_matrix.T), weights)))
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 16 is different from 8)
```

**Cause**

The MGH scanner has been expanded to 16 Tx channels, therefore the SarDataUser.mat contains a VOP file (ZZ) that is 16x16x100 in size, compared to 8x8x167 for the MNI. Hence ` (size 16 is different from 8)`, and the execution stops there. 

**Steps to remedy**
I have asked Siemens what the mapping of Tx channels in SarDataUser.mat is to the Tx numbering for coils, I will update once we have an answer. I have a _suspicion_ that it is the upper left 8x8 elements of the 16x16 matrix (so the elements are numbered 1-16), but I am not sure.

**Comment by dpapp86** [comment]
Important update from Kyle Gilbert:

The SarDatuser.mat is regenerated every time Siemens RF shimming is called. But, if previously a different coil was used (say a 16Tx channel one) then there is currently no way to check if the coil and the VOP files match. So this is less of a bug for the Toolbox, but for the workflow.

**Comment by jcohenadad** [comment]
Thank you for documenting this @dpapp86
