### ISSUE TITLE
B1+ demo data does not convert properly using st_dicom_to_nifti

### ISSUE THREAD

**Issue by dpapp86** [shimming-toolbox/shimming-toolbox#557]
"Happy to see this is still going!

I ran into this issue when I wanted to pick B1+ shimming back up for a project. I was not able to run the data conversion step of the tutorial without issues, and the resulting converted nifti file was not loaded into fsleyes with the "singleton dimension" error that I am familiar with from Gaspard's issues here [#283](https://github.com/shimming-toolbox/shimming-toolbox/pull/283):
(note that this issue and the singleton dimension issue might be unrelated)

**Error dump:**

` st_dicom_to_nifti -i data_b1_shimming/dicoms/ --subject test -o output_dicom_to_nifti/ --config /home/z004u75t/shiminstall/shimming-toolbox/shimming-toolbox/config/dcm2bids.json
INFO:shimmingtoolbox.dicom_to_nifti:dcm2bids version: 3.2.0
INFO:dcm2bids.utils.tools:Currently using the latest version of dcm2bids.
INFO:dcm2bids.utils.utils:Running: dcm2niix -b y -ba y -z y -f %3s_%f_%p_%t -o output_dicom_to_nifti/tmp_dcm2bids/sub-test data_b1_shimming/dicoms
INFO:dcm2bids.dcm2niix_gen:Log from dcm2niix execution
WARNING:dcm2bids.dcm2niix_gen:Chris Rorden's dcm2niiX version v1.0.20240202 GCC12.3.0 x86-64 (64-bit Linux)
Found 512 DICOM file(s)
Warning: Images sorted by instance number [0020,0013](https://github.com/shimming-toolbox/shimming-toolbox/issues/1..512), but AcquisitionTime [0008,0032] suggests a different order (130102..130102)
Warning: Unable to determine slice direction: please check whether slices are flipped
Convert 512 DICOM as output_dicom_to_nifti/tmp_dcm2bids/sub-test/002_dicoms_standard_-_b1map_20220215124904 (96x96x32x16)
Conversion required 0.418106 seconds (0.418099 for core code).

Traceback (most recent call last):
File "/home/z004u75t/shimming-toolbox/bin/st_dicom_to_nifti", line 33, in
sys.exit(load_entry_point('shimmingtoolbox', 'console_scripts', 'st_dicom_to_nifti')())
File "/home/z004u75t/shimming-toolbox/python/lib/python3.10/site-packages/click/core.py", line 1157, in call
return self.main(*args, **kwargs)
File "/home/z004u75t/shimming-toolbox/python/lib/python3.10/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/home/z004u75t/shimming-toolbox/python/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/z004u75t/shimming-toolbox/python/lib/python3.10/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "/home/z004u75t/shiminstall/shimming-toolbox/shimming-toolbox/shimmingtoolbox/cli/dicom_to_nifti.py", line 34, in dicom_to_nifti_cli
dicom_to_nifti(path_dicom=path_dicom,
File "/home/z004u75t/shiminstall/shimming-toolbox/shimming-toolbox/shimmingtoolbox/dicom_to_nifti.py", line 70, in dicom_to_nifti
Dcm2BidsGen(path_dicom, subject_id, fname_config_dcm2bids, path_nifti).run()
File "/home/z004u75t/shimming-toolbox/python/lib/python3.10/site-packages/dcm2bids/dcm2bids_gen.py", line 116, in run
parser.build_graph()
File "/home/z004u75t/shimming-toolbox/python/lib/python3.10/site-packages/dcm2bids/sidecar.py", line 274, in build_graph
if criteria and self.isLink(sidecar.data, criteria):
File "/home/z004u75t/shimming-toolbox/python/lib/python3.10/site-packages/dcm2bids/sidecar.py", line 400, in isLink
result.append(compare(name, pattern))
File "/home/z004u75t/shimming-toolbox/python/lib/python3.10/site-packages/dcm2bids/sidecar.py", line 294, in compare
return bool(re.match(pattern, name))
File "/home/z004u75t/shimming-toolbox/python/lib/python3.10/re.py", line 190, in match
return _compile(pattern, flags).match(string)
File "/home/z004u75t/shimming-toolbox/python/lib/python3.10/re.py", line 293, in _compile
return _cache[type(pattern), pattern, flags]
TypeError: unhashable type: 'list'
`

**Sysinfo:**
System 1: My old Polytechnique Mac, Python 3.12.3, fresh ST install from github at time of writing

System 2: A VM running in VMWare, Ubuntu 24, Python 3.12.3, fresh ST install from github at time of writing

**Reproduction steps:**
Follow the instructions on https://shimming-toolbox.org/en/latest/user_section/tutorials/b1_shimming.html, or run an equivalent command line command

**Sanity checks**

I used st_dicom_to_nifti on both VE12 and XA60 non-B1map data, and found no issues

**Comment by po09i** [comment]
The main issue seems to be on dcm2bids side, I opened an [issue](https://github.com/UNFmontreal/Dcm2Bids/issues/321) there. The problem is that the "ImageType” field is not populated by dcm2niix for this sequence and dcm2bids does not like it when their configuration file compares a list to something that does not exists. There is a line in the code that says the default value should be "" which is a mismatch when compared to a list.

**Comment by po09i** [comment]
This just got fixed in their dev version. Waiting for a version bump.

**Comment by FeiyangLou** [comment]
Hello developers, I tried to run the tutorial https://shimming-toolbox.org/en/latest/user_section/tutorials/b1_shimming.html today and met the exact same issue here.

**Comment by po09i** [comment]
@FeiyangLou You are correct, thanks for reporting it. The tutorial is not working due to an upstream issue with dcm2bids. We are still waiting for a version bump. I am working on updating the tutorial to streamline it a little and provide a workaround in the meantime. The workaround should be available soon.

**Comment by FeiyangLou** [comment]
> [@FeiyangLou](https://github.com/FeiyangLou) You are correct, thanks for reporting it. The tutorial is not working due to an upstream issue with dcm2bids. We are still waiting for a version bump. I am working on updating the tutorial to streamline it a little and provide a workaround in the meantime. The workaround should be available soon.

Thank you! One more little question: do I have to reinstall the whole shimming toolbox after fixing this dcm2bids problem?

**Comment by po09i** [comment]
@FeiyangLou 
> Thank you! One more little question: do I have to reinstall the whole shimming toolbox after fixing this dcm2bids problem?

We recommend updating Shimming Toolbox as a whole so that your version is in sync with the GitHub versions (it makes it easier if you encounter an issue if you have a standard installation).

To update, simply:
```
cd <shimming-toolbox-repo-directory>
git checkout master
git pull
make install
```

The updated B1 shimming tutorial is now live. The dcm2bids issue is still present since they have not released an updated version. That means that there will be an error message when hitting run when using `st_dicom_to_nifti`. While we wait for an update, you can place this folder at this location: "<your-local-path>/data_b1_shimming/niftis" once you reach that error. Unzip the folder at the same location. You should be able to complete the rest of the tutorial without any error after this modification.

To perform the tutorial, you should update to a version released after 2025/02/14. You can update using the commands above.

[sub-test.zip](https://github.com/user-attachments/files/18805040/sub-test.zip)

**Comment by FeiyangLou** [comment]
> [@FeiyangLou](https://github.com/FeiyangLou)
> 
> > Thank you! One more little question: do I have to reinstall the whole shimming toolbox after fixing this dcm2bids problem?
> 
> We recommend updating Shimming Toolbox as a whole so that your version is in sync with the GitHub versions (it makes it easier if you encounter an issue if you have a standard installation).
> 
> To update, simply:
> 
> ```
> cd <shimming-toolbox-repo-directory>
> git checkout master
> git pull
> make install
> ```
> 
> The updated B1 shimming tutorial is now live. The dcm2bids issue is still present since they have not released an updated version. That means that there will be an error message when hitting run when using `st_dicom_to_nifti`. While we wait for an update, you can place this folder at this location: "/data_b1_shimming/niftis" once you reach that error. Unzip the folder at the same location. You should be able to complete the rest of the tutorial without any error after this modification.
> 
> To perform the tutorial, you should update to a version released after 2025/02/14. You can update using the commands above.
> 
> [sub-test.zip](https://github.com/user-attachments/files/18805040/sub-test.zip)

Really thanks for all this! I've successfully gone through the tutorial procedure now.
